---
  - name: "Playing with Ansible and Git"
    hosts: localhost
    connection: local
    #vars_files:
    #  - vars/main.yaml

    tasks:
      #- name: install taskfile
      #  apt:
      #    deb: https://github.com/go-task/task/releases/download/v3.33.1/task_linux_amd64.deb
      #  become: true

      - name: place vimrc file
        ansible.builtin.copy:
          src: vimrc
          dest: /home/tim/.vimrc
          owner: tim
          group: tim 
          mode: '0644'

      - name: place bash_profile file
        ansible.builtin.copy:
          src: bash_profile
          dest: /home/tim/.bash_profile
          owner: tim
          group: tim 
          mode: '0644'

      - name: install kubectl
        include_tasks: k8s_tools.yaml
