execute pathogen#infect()
set expandtab 
set number
set tabstop=2
set shiftwidth=2
syntax on
map <C-n> :NERDTreeToggle<CR>
set omnifunc=syntaxcomplete#Complete
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif
